```{r}
library(tidyverse)
library(readxl)
library(ggpubr)
library(survival)
library(ggsurvfit)
library(survminer)
library(patchwork)
```

```{r}
survival.metadata <- read_csv("survival_metadata.csv")
print(nrow(survival.metadata))
print(median(survival.metadata$RFS_months))
print(max(survival.metadata$RFS_months))
#survival.metadata
```


# stratify by pathological response
```{r}
#==========all patients =============
fit.data <- survival.metadata %>% mutate(MPR_pPR_nPR=ifelse(PRR_group=="pCR", "MPR", PRR_group))

fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ factor(fit.data$MPR_pPR_nPR, levels = c("MPR", "pPR", "nPR")), data = fit.data)
summary(fit.cox)

fit <- survfit(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ fit.data$MPR_pPR_nPR, data = fit.data)
print(fit)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "",
          palette = c("#077E64", "#C6595A", "#878586")
) 
p
ggsave("plots/all_patients_MPR_pPR_nPR.pdf", width = 8, height = 6)
```


# stratify by nTregClone
```{r}
#==========all patients =============
fit.data <- survival.metadata %>% 
  filter(!is.na(numberTregClone)) %>% 
  mutate(Treggroup= ifelse(numberTregClone>3, "activated Treg clone ≥4", "activated Treg clone <4"))

fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ factor(fit.data$Treggroup), data = fit.data)
summary(fit.cox)

fit <- survfit(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ fit.data$Treggroup, data = fit.data)
print(fit)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all_patients_by_Treg_clones",
          palette =  c("#077E64", "#C6595A")
)
p

ggsave("plots/all_patients_by_Treg_clones.pdf", width = 8, height = 6)
```

# stratify by tex clone in low tolerance patients
```{r}
fit.data <- survival.metadata %>% filter(!is.na(numberTexClone)) %>% 
  mutate(textreg= ifelse(MPR=="MPR", "MPR", ifelse(numberTregClone>=4, "Tregclone>=4", ifelse(numberTexClone<=1, "Tregclone<4, Tex<1", "Tregclone<4Tex>1")))) %>% filter(textreg %in% c("Tregclone<4, Tex<1", "Tregclone<4Tex>1"))
  
#================
fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ factor(fit.data$textreg, levels = c("Tregclone<4Tex>1", "Tregclone<4, Tex<1")), data = fit.data)
summary(fit.cox)

fit <- survfit(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ fit.data$textreg, data = fit.data)
print(fit)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "",
          palette = c("#C6595A", "#077E64")
)


p
ggsave("plots/low_tolerance_patients_by_Tex_clonotype_number.pdf", height = 6, width = 8)
```


# stratify by immune risk
```{r}
fit.data <- survival.metadata %>% filter(!is.na(numberTexClone)) %>% 
  mutate(textreg= ifelse(MPR=="MPR", "MPR", ifelse(numberTregClone>=4, "Tregclone>=4", ifelse(numberTexClone<=1, "Tregclone<4, Tex<1", "Tregclone<4Tex>1")))) %>%
  mutate(
  immune_risk = ifelse(textreg %in% c("MPR", "Tregclone<4Tex>1"), "low", "high"),
  RVT = 100* (1- `Pathological Response Rate`),
  PRR_rate = 100*`Pathological Response Rate`
)

#================
fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ factor(fit.data$textreg, levels = c("MPR", "Tregclone<4Tex>1", "Tregclone<4, Tex<1", "Tregclone>=4")), data = fit.data)
summary(fit.cox)

fit <- survfit(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ fit.data$textreg, data = fit.data)
print(fit)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all_patients_by_immune_sub_group",
          palette = c("#077E64", "#C6595A", "#00C598", "#878586")
)


p
ggsave("plots/all_patients_by_immune_subgroup.pdf", height = 6, width = 8)


#=================
fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ factor(fit.data$immune_risk, levels = c("low", "high")), data = fit.data)
summary(fit.cox)

fit <- survfit(Surv(fit.data$RFS_months, fit.data$RFS_status) ~ fit.data$immune_risk, data = fit.data)
print(fit)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all_patients_by_immune_risk",
          palette = c("#C6595A", "#077E64")
)


p
ggsave("plots/all_patients_by_immune_risk.pdf", height = 6, width = 8)
```

# univariate & multivariate analysis of PRR rate & immune risk
```{r}
fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~  fit.data$PRR_rate, data = fit.data)
summary(fit.cox)

fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~  factor(fit.data$immune_risk, levels=c("low", "high")), data = fit.data)
summary(fit.cox)

fit.cox <- coxph(Surv(fit.data$RFS_months, fit.data$RFS_status) ~  fit.data$PRR_rate + factor(fit.data$immune_risk, levels=c("low", "high")), data = fit.data)
summary(fit.cox)
```























