```{r}
library(tidyverse)
library(ggpubr)
library(ggplot2)

# note this has ICI+chemo patients, and chemo-only patients
metadata.lusc.luad.no.egfr.alk <- read_csv("clean_metadata_all_surgical_sample_lusc_luad_only_excluded_egfr_alk.csv")

nrow(metadata.lusc.luad.no.egfr.alk)

table.for.clinical.metadata.summary <- metadata.lusc.luad.no.egfr.alk %>% 
  filter(`Pathological Response` %in% c("MPR", "non-MPR", "pCR")) %>%
  filter(!is.na(PD1))

table.for.clinical.metadata.summary
```

```{r}
table.for.clinical.metadata.regression <- table.for.clinical.metadata.summary[c(
  "Age", "Gender", "issmoke", "pathology", "Platinum","Cycles", "Pathological Response",
  "center", "PD1", "Chemotherapy", "before_N", "PD-L1TPS", "Pre-treatment Staging",
  "grouped_staging")]
table.for.clinical.metadata.regression <- table.for.clinical.metadata.regression %>% filter(!PD1=="No")

table.for.clinical.metadata.regression <- table.for.clinical.metadata.regression %>% mutate(
  `Pathological Response`=ifelse(`Pathological Response` %in% c("MPR", "pCR"), "MPR", "non-MPR"),
  Age=ifelse(Age<=65, "<=65", ">65"),
  Platinum=ifelse(Platinum=="Carboplatin", "Carboplatin", 
                  ifelse(Platinum=="Cisplatin", "Cisplatin", "others")),
  Cycles=ifelse(Cycles=="2", "2 cycles",
                ifelse(Cycles=="3", "3 cycles",
                       ifelse(Cycles=="4", "4 cycles", "others"))),
  PD1=ifelse(grepl("Pembrolizumab", PD1), "Pembrolizumab", 
             ifelse(grepl("Nivolumab", PD1), "Nivolumab", 
                    ifelse(grepl("Sintilimab", PD1), "Sintilimab", 
                           ifelse(grepl("Tislelizumab", PD1), "Tislelizumab", 
                                  ifelse(grepl("Camrelizumab", PD1), "Camrelizumab", "others"))))),
  second_chemotherapy=ifelse(Chemotherapy=="No", "No", 
                             ifelse(grepl("Paclitaxel", Chemotherapy), "Paclitaxel",
                                    ifelse(grepl("Abraxane", Chemotherapy), "Paclitaxel",
                                           ifelse(grepl("Docetaxel", Chemotherapy), "Paclitaxel",
                                                  ifelse(grepl("Gemcitabine", Chemotherapy), "Gemcitabine",
                                                         ifelse( grepl("Pemetrexed", Chemotherapy), "Pemetrexed",
                                                                ifelse(is.na(Chemotherapy), "others", "others"))))))),
  `PD-L1TPS`=ifelse(`PD-L1TPS`<0.01, "<1%", 
                    ifelse(`PD-L1TPS`>=0.5, ">=50%", "1~50%"))
)

table.for.clinical.metadata.regression <- table.for.clinical.metadata.regression %>% 
  filter(!PD1=="others") %>% 
  filter(!Cycles=="others") %>% 
  filter(!second_chemotherapy=="No") %>%
  filter(!second_chemotherapy=="others") %>%
  filter(!grouped_staging=="not available")


table.for.clinical.metadata.regression <- table.for.clinical.metadata.regression[c(
  "Age", "Gender", "issmoke", "pathology", "Platinum","Cycles",
  "center", "PD1", "before_N", "PD-L1TPS", "Pathological Response", "second_chemotherapy",
  "grouped_staging")]
table.for.clinical.metadata.regression

write.csv(table.for.clinical.metadata.regression, "metadata_table_cleaned_for_regression_analysis.csv")
```

```{r}
library("autoReg")
library("dplyr")
library("ggplot2")
library("ggpubr")
library("ggsci")

regression_table <- read.csv("metadata_table_cleaned_for_regression_analysis.csv")
regression_table <- regression_table %>% mutate(Pathological.Response=ifelse(Pathological.Response=="MPR", 1, 0))
regression_table
```

```{r}
LUSC.regression_table <- regression_table %>% filter(pathology == "LUSC")
LUAD.regression_table <- regression_table %>% filter(pathology == "LUAD")

nrow(LUSC.regression_table)
sapply(LUSC.regression_table, function(x) sum(is.na(x)))

nrow(LUAD.regression_table)
sapply(LUAD.regression_table, function(x) sum(is.na(x)))
```


```{r}
LUSC.LUAD.overall.log <- glm(Pathological.Response ~ Age + Gender + issmoke + Platinum +
                                           Cycles + center + pathology + PD1 + before_N + second_chemotherapy +
                                           grouped_staging, data=regression_table, family=binomial) 


summary(LUSC.LUAD.overall.log)
#LUSC.LUAD.result<-autoReg(LUSC.LUAD.overall.log,uni=TRUE,multi=TRUE, threshold=0.01)
#LUSC.LUAD.result %>% myft()

#myplot <- modelPlot(LUSC.LUAD.overall.log, uni=TRUE, show.ref = TRUE, threshold=0.01,   change.pointsize = T)
#myplot$p <- myplot$p + scale_fill_nejm() + scale_color_nejm()
#myplot


#summary(LUSC.LUAD.overall.log)
LUSC.LUAD.result<-autoReg(LUSC.LUAD.overall.log,uni=TRUE,multi=FALSE, threshold=0.01)
LUSC.LUAD.result %>% myft()

myplot <- modelPlot(LUSC.LUAD.overall.log, uni=TRUE, multi=FALSE, show.ref = TRUE, threshold=0.01,   change.pointsize = T)
myplot
#myplot$p <- myplot$p + scale_fill_nejm() + scale_color_nejm()
#myplot

ggsave("metadata_regression_analysis.pdf")
```


```{r}
#========
LUSC.overall.log <- glm(Pathological.Response ~ Age + Gender + issmoke + Platinum +
                                           Cycles + center + PD1 + before_N + second_chemotherapy +
                                           grouped_staging, data=LUSC.regression_table, family=binomial) 


summary(LUSC.overall.log)
LUSC.result<-autoReg(LUSC.overall.log,uni=TRUE,multi=TRUE,threshold=0.1)
LUSC.result
```


```{r}
#=====

LUAD.overall.log <- glm(Pathological.Response ~ Age + Gender + issmoke + Platinum +
                                           Cycles + center + PD1 + before_N + second_chemotherapy +
                                           grouped_staging, data=LUAD.regression_table, family=binomial) 

summary(LUAD.overall.log)
LUAD.result<-autoReg(LUAD.overall.log,uni=TRUE,multi=TRUE,threshold=0.1)
LUAD.result
```

#===== analyze PDL1 only
```{r}
LUSC.PDL1.log <- glm(Pathological.Response ~ PD.L1TPS, data=LUSC.regression_table, family=binomial) 


summary(LUSC.PDL1.log)
LUSC.PDL1.result<-autoReg(LUSC.PDL1.log,uni=TRUE, multi=FALSE, threshold=1)
LUSC.PDL1.result

myplot <- modelPlot(LUSC.PDL1.log, uni=TRUE, show.ref = TRUE, multi=FALSE, threshold=1,   change.pointsize = T)
myplot
ggsave("LUSC_PD-L1_regression_analysis.pdf")
```


```{r}
LUAD.PDL1.log <- glm(Pathological.Response ~ PD.L1TPS, data=LUAD.regression_table, family=binomial) 

summary(LUAD.PDL1.log)
LUAD.PDL1.result<-autoReg(LUAD.PDL1.log,uni=TRUE, multi=FALSE, threshold=1)
LUAD.PDL1.result

myplot <- modelPlot(LUAD.PDL1.log, uni=TRUE, show.ref = TRUE, multi=FALSE, threshold=1,   change.pointsize = T)
myplot
ggsave("LUAD_PD-L1_regression.pdf", height = 5, width = 15)
```

