```{r}
library(tidyverse)
library(dplyr)
library(readxl)
library(ggpubr)
library(survival)
library(ggsurvfit)
library(survminer)
library(risksetROC)
library(forestplot)
```

```{r}
survival.metadata.clean <- read_csv("survival.metadata.final.csv") %>% mutate(MPR_pPR_nPR=ifelse(PRR_group=="pCR", "MPR", PRR_group))
survival.metadata.clean
```


```{r}
survival.metadata.clean %>% dplyr::group_by(histology) %>% count(MPR)
```

```{r}
survival.metadata.clean %>% group_by(TCR.classification) %>% count(RFS_status)
survival.metadata.clean %>% group_by(TCR.classification) %>% count(is.na(numberTexClone))
survival.metadata.clean %>% group_by(TCR.classification) %>% count(numberTexClone==0)
survival.metadata.clean %>% group_by(TCR.classification) %>% count(is.na(Texp.in.Tex.relevant))
```


### global analysis of risk factors
```{r}
fit.data <- survival.metadata.clean

#fit.data <- fit.data %>% mutate(filter=ifelse(new_group==1 & MPR=="MPR", TRUE, FALSE)) %>% filter(filter==FALSE)

covariates <- c("histology", "PRR", "numberTexClone", "numberTregClone", "Texp.in.Tex.relevant", "Treg_CCR8" )
univ_formulas <- sapply(covariates,
                        function(x) as.formula(paste('Surv(RFS_months_new, RFS_status_new)~', x)))
                        
univ_models <- lapply( univ_formulas, function(x){coxph(x, data = fit.data)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                          x <- summary(x)
                          p.value<-signif(x$wald["pvalue"], digits=2)
                          #wald.test<-signif(x$wald["test"], digits=2)
                          #beta<-signif(x$coef[1], digits=2);#coeficient beta
                          HR <-signif(x$coef[2], digits=2);#exp(beta)
                          HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                          HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                          # HR <- paste0(HR, " (", 
                          #             HR.confint.lower, "-", HR.confint.upper, ")")
                          res<-c(HR, HR.confint.lower, HR.confint.upper, p.value)
                          names(res)<-c("HR", "HR.lower", "HR.upper", 
                                        "p.value")
                          return(res)
                          #return(exp(cbind(coef(x),confint(x))))
                         })
univ_results
result <- as.data.frame(univ_results)
result <- as.data.frame(t(result))
result #%>% filter(p.value <0.05)

tabletext1<-as.character(rownames(result))
tabletext2<-as.numeric(result[,"p.value"])
tabletext<-cbind(tabletext1,tabletext2)


pdf("final_plots/all.patients.HR.pdf",         # File name
    width = 8, height = 5, # Width and height in inches
    bg = "white",          # Background color
    colormodel = "RGB",    # Color model (cmyk is required for most publications)
    paper = "A4")          # Paper size

# Closing the graphical device

forestplot(labeltext=tabletext, #文本信息  
           mean = result[,'HR'],##HR值
lower = result[,"HR.lower"],##95%置信区间
upper = result[,"HR.upper"],#95%置信区间
           boxsize = 0.1,##大小
           graph.pos=3,#图在表中的列位置
           graphwidth = unit(0.4,"npc"),#图在表中的宽度比例
           #fn.ci_norm="fpDrawDiamondCI",#box类型选择钻石,可以更改fpDrawNormalCI；fpDrawCircleCI等
col=fpColors(box="steelblue", lines="black", zero = "black"),#颜色设置
           lwd.ci=2,ci.vertices.height = 0.1,ci.vertices=TRUE,#置信区间用线宽、高、型
           zero=1,#zero线横坐标
           lwd.zero=2,#zero线宽
           grid=T,
           lwd.xaxis=2,#X轴线宽
           title="Hazard Ratio",
           xlab="",#X轴标题
           clip=c(-Inf,4),#边界
           colgap = unit(0.5,"cm")   
)
dev.off()
```


```{r}
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$PRR + fit.data$Texp.in.Tex.relevant + fit.data$Treg_CCR8, data = fit.data)
summary(fit.cox)
```


```{r}
pdf("final_plots/all.patients.ROC.pdf",         # File name
    width = 5, height = 5, # Width and height in inches
    bg = "white",    # Color model (cmyk is required for most publications)
    paper = "A4")  
fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant))
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Texp.in.Tex.relevant, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf.texp <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months), method="Cox",col="#418849",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
tROC.hf.texp$AUC


fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant))
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$PRR, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf.prr <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months), method="Cox",col="blue",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
tROC.hf.prr$AUC


lines(tROC.hf.texp$FP, tROC.hf.texp$TP, type="l",col="#418849",xlim=c(0,1), ylim=c(0,1))
lines(tROC.hf.prr$FP, tROC.hf.prr$TP, type="l",col="blue",xlim=c(0,1), ylim=c(0,1))
legend("bottomright",c(paste("AUC of texp: ",round(tROC.hf.texp$AUC,3)), paste("AUC of PRR : ",round(tROC.hf.prr$AUC,3))),col=c("#418849","blue"),lty=1,lwd=2,bty = "n") 
dev.off()
```


```{r}
fit.data <- survival.metadata.clean %>% mutate(numberTregClone.bin= ifelse(
  numberTregClone <as.vector(quantile(numberTregClone, na.rm=T)[4]), "<top 25%", ">= top25%" # the quantile of survival analysis cohort and nmf cohort are almost the same quantile.
))

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$numberTregClone.bin, data = fit.data)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all.patients.numberTregClone",
          palette =  c("#077E64", "#C6595A")
)
p
ggsave("final_plots/all.patients.numberTregClone.pdf", width = 8, height = 6)

# 0.235771 0.291866 0.342278 0.520000 
#===============
fit.data <- survival.metadata.clean %>% mutate(Treg_CCR8.bin= ifelse(
  Treg_CCR8 <as.vector(quantile(Treg_CCR8, na.rm=T)[2]),
  #Treg_CCR8 < 0.235771, 
  "<top 75%", ">= top75%" # the quantile of survival analysis cohort and nmf cohort are almost the same
  ))

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$Treg_CCR8.bin, data = fit.data)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all.patients.CCR8Treg.in.allTreg",
          palette =  c("#077E64", "#C6595A")
)
p
ggsave("final_plots/all.patients.CCR8Treg.in.allTreg.pdf", width = 8, height = 6)
#============


#==========
fit.data <- survival.metadata.clean %>% mutate(Texp.in.Tex.relevant.bin= ifelse(
  Texp.in.Tex.relevant <as.vector(quantile(Texp.in.Tex.relevant, na.rm=T)[2]),
  #Texp.in.Tex.relevant < 0.7592234, 
  "<top 75%", ">= top75%" # the quantile of survival analysis cohort and nmf cohort are almost the same
))

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$Texp.in.Tex.relevant.bin, data = fit.data)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all.patients.Texp",
          palette =  c( "#C6595A","#077E64")
)
p
ggsave("final_plots/all.patients.Texp.pdf", width = 8, height = 6)
#============

#========
fit.data <- survival.metadata.clean
fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$MPR_pPR_nPR, data = fit.data)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all_patients_by_PRR",
          palette = c("#077E64", "#C6595A", "#878586")
)
p
ggsave("final_plots/all.patients.PRR.pdf", width = 8, height = 6)
#============

#======
fit.data <- survival.metadata.clean
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  as.factor(fit.data$new_group), data = fit.data)
summary(fit.cox)

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ as.factor(fit.data$new_group), data = fit.data)
print(fit)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all_patients_by_TIME",
          palette =  c("#E64B35", "#4DBBD5", "#00A087", "#3C5488", "#F39B7F")
)
p
ggsave("final_plots/all.patients.TIME.pdf", width = 8, height = 6)
```


### focusing on non-MPR patients
```{r}
fit.data <- survival.metadata.clean 

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$TCR.classification, data = fit.data)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all_patients_by_non-MPR_subtype",
          palette = c("#D9BFAE", "#8CB4A3", "#7998AD")
)
p

ggsave("final_plots/all.patients.non-MPR.subtype.pdf", width = 8, height = 6)
```


### type I patients
```{r}
fit.data <- survival.metadata.clean %>% filter(TCR.classification=="type I")

#fit.data <- fit.data %>% mutate(filter=ifelse(new_group==1 & MPR=="MPR", TRUE, FALSE)) %>% filter(filter==FALSE)

covariates <- c("histology","PRR","numberTexClone", "numberTregClone", "Texp.in.Tex.relevant", "Treg_CCR8")
univ_formulas <- sapply(covariates,
                        function(x) as.formula(paste('Surv(RFS_months_new, RFS_status_new)~', x)))
                        
univ_models <- lapply( univ_formulas, function(x){coxph(x, data = fit.data)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                          x <- summary(x)
                          p.value<-signif(x$wald["pvalue"], digits=2)
                          #wald.test<-signif(x$wald["test"], digits=2)
                          #beta<-signif(x$coef[1], digits=2);#coeficient beta
                          HR <-signif(x$coef[2], digits=2);#exp(beta)
                          HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                          HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                          # HR <- paste0(HR, " (", 
                          #             HR.confint.lower, "-", HR.confint.upper, ")")
                          res<-c(HR, HR.confint.lower, HR.confint.upper, p.value)
                          names(res)<-c("HR", "HR.lower", "HR.upper", 
                                        "p.value")
                          return(res)
                          #return(exp(cbind(coef(x),confint(x))))
                         })
univ_results
result <- as.data.frame(univ_results)
result <- as.data.frame(t(result))
result #%>% filter(p.value <0.05)

tabletext1<-as.character(rownames(result))
tabletext2<-as.numeric(result[,"p.value"])
tabletext<-cbind(tabletext1,tabletext2)

pdf("final_plots/typeI.patients.HR.pdf",         # File name
    width = 8, height = 5, # Width and height in inches
    bg = "white",          # Background color
    colormodel = "RGB",    # Color model (cmyk is required for most publications)
    paper = "A4")          # Paper size
forestplot(labeltext=tabletext, #文本信息  
           mean = result[,'HR'],##HR值
lower = result[,"HR.lower"],##95%置信区间
upper = result[,"HR.upper"],,#95%置信区间
           boxsize = 0.1,##大小
           graph.pos=3,#图在表中的列位置
           graphwidth = unit(0.4,"npc"),#图在表中的宽度比例
           #fn.ci_norm="fpDrawDiamondCI",#box类型选择钻石,可以更改fpDrawNormalCI；fpDrawCircleCI等
col=fpColors(box="steelblue", lines="black", zero = "black"),#颜色设置
           lwd.ci=2,ci.vertices.height = 0.1,ci.vertices=TRUE,#置信区间用线宽、高、型
           zero=1,#zero线横坐标
           lwd.zero=2,#zero线宽
           grid=T,
           lwd.xaxis=2,#X轴线宽
           title="Hazard Ratio",
           xlab="",#X轴标题
           clip=c(-Inf,4),#边界
           colgap = unit(0.5,"cm")   
)
dev.off()


fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Surgery_N, data = fit.data)
summary(fit.cox)

fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Surgery_N + fit.data$Texp.in.Tex.relevant, data = fit.data)
summary(fit.cox)
```

```{r}
fit.data <- survival.metadata.clean %>% filter(TCR.classification=="type I") %>% mutate(Texp.in.Tex.relevant.bin= ifelse(
  #Texp.in.Tex.relevant < 0.7592234, 
  Texp.in.Tex.relevant < as.vector(quantile(Texp.in.Tex.relevant,na.rm=T)[3]),
  "<top 25%", ">= top25%" # the quantile of survival analysis cohort and nmf cohort are almost the same
))

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$Texp.in.Tex.relevant.bin, data = fit.data)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "typeI.non-MPR.by.Texp",
          palette =  c("#C6595A", "#077E64")
)
p
ggsave("final_plots/typeI.non-MPR.by.Texp.pdf", width = 8, height = 6)
```


### type II non-MPR patients 
```{r}
fit.data <- survival.metadata.clean %>% filter(TCR.classification=="type II")

#fit.data <- fit.data %>% mutate(filter=ifelse(new_group==1 & MPR=="MPR", TRUE, FALSE)) %>% filter(filter==FALSE)

covariates <- c("histology","PRR","numberTexClone", "numberTregClone", "Texp.in.Tex.relevant", "Treg_CCR8")
univ_formulas <- sapply(covariates,
                        function(x) as.formula(paste('Surv(RFS_months_new, RFS_status_new)~', x)))
                        
univ_models <- lapply( univ_formulas, function(x){coxph(x, data = fit.data)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                          x <- summary(x)
                          p.value<-signif(x$wald["pvalue"], digits=2)
                          #wald.test<-signif(x$wald["test"], digits=2)
                          #beta<-signif(x$coef[1], digits=2);#coeficient beta
                          HR <-signif(x$coef[2], digits=2);#exp(beta)
                          HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                          HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                          # HR <- paste0(HR, " (", 
                          #             HR.confint.lower, "-", HR.confint.upper, ")")
                          res<-c(HR, HR.confint.lower, HR.confint.upper, p.value)
                          names(res)<-c("HR", "HR.lower", "HR.upper", 
                                        "p.value")
                          return(res)
                          #return(exp(cbind(coef(x),confint(x))))
                         })
univ_results
result <- as.data.frame(univ_results)
result <- as.data.frame(t(result))
result #%>% filter(p.value <0.05)

tabletext1<-as.character(rownames(result))
tabletext2<-as.numeric(result[,"p.value"])
tabletext<-cbind(tabletext1,tabletext2)

pdf("final_plots/typeII.patients.HR.pdf",         # File name
    width = 8, height = 5, # Width and height in inches
    bg = "white",          # Background color
    colormodel = "RGB",    # Color model (cmyk is required for most publications)
    paper = "A4")          # Paper size
forestplot(labeltext=tabletext, #文本信息  
           mean = result[,'HR'],##HR值
lower = result[,"HR.lower"],##95%置信区间
upper = result[,"HR.upper"],,#95%置信区间
           boxsize = 0.1,##大小
           graph.pos=3,#图在表中的列位置
           graphwidth = unit(0.4,"npc"),#图在表中的宽度比例
           #fn.ci_norm="fpDrawDiamondCI",#box类型选择钻石,可以更改fpDrawNormalCI；fpDrawCircleCI等
col=fpColors(box="steelblue", lines="black", zero = "black"),#颜色设置
           lwd.ci=2,ci.vertices.height = 0.1,ci.vertices=TRUE,#置信区间用线宽、高、型
           zero=1,#zero线横坐标
           lwd.zero=2,#zero线宽
           grid=T,
           lwd.xaxis=2,#X轴线宽
           title="Hazard Ratio",
           xlab="",#X轴标题
           clip=c(-Inf,4),#边界
           colgap = unit(0.5,"cm")   
)
dev.off()

fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Surgery_N, data = fit.data)
summary(fit.cox)


```

```{r}
fit.data <- survival.metadata.clean %>% filter(TCR.classification=="type II") %>% mutate(Texp.in.Tex.relevant.bin= ifelse(
  #Texp.in.Tex.relevant < 0.7592234, 
  Texp.in.Tex.relevant < as.vector(quantile(Texp.in.Tex.relevant,na.rm=T)[3]),
  "<top 25%", ">= top25%" # the quantile of survival analysis cohort and nmf cohort are almost the same
))

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$Texp.in.Tex.relevant.bin, data = fit.data)

p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "typeII.non-MPR.by.subtypes",
          palette =  c("#C6595A", "#077E64")
)
p
ggsave("final_plots/typeII.non-MPR.by.Texp.pdf", width = 8, height = 6)
```


### MPR patients
```{r}
fit.data <- survival.metadata.clean %>% filter(TCR.classification=="MPR")

#fit.data <- fit.data %>% mutate(filter=ifelse(new_group==1 & MPR=="MPR", TRUE, FALSE)) %>% filter(filter==FALSE)

covariates <- c("numberTexClone", "numberTregClone", "Texp.in.Tex.relevant", "Treg_CCR8", "PRR", "histology")
univ_formulas <- sapply(covariates,
                        function(x) as.formula(paste('Surv(RFS_months_new, RFS_status_new)~', x)))
                        
univ_models <- lapply( univ_formulas, function(x){coxph(x, data = fit.data)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                          x <- summary(x)
                          p.value<-signif(x$wald["pvalue"], digits=2)
                          wald.test<-signif(x$wald["test"], digits=2)
                          beta<-signif(x$coef[1], digits=2);#coeficient beta
                          HR <-signif(x$coef[2], digits=2);#exp(beta)
                          HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                          HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                          HR <- paste0(HR, " (", 
                                       HR.confint.lower, "-", HR.confint.upper, ")")
                          res<-c(beta, HR, wald.test, p.value)
                          names(res)<-c("beta", "HR (95% CI for HR)", "wald.test", 
                                        "p.value")
                          return(res)
                          #return(exp(cbind(coef(x),confint(x))))
                         })
univ_results
result <- as.data.frame(univ_results)
result <- as.data.frame(t(result))
result #%>% filter(p.value <0.05)


fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Surgery_N, data = fit.data)
summary(fit.cox)
```

### all non-MPR patients
```{r}
fit.data <- survival.metadata.clean %>% filter(TCR.classification %in% c("type I", "type II"))

#fit.data <- fit.data %>% mutate(filter=ifelse(new_group==1 & MPR=="MPR", TRUE, FALSE)) %>% filter(filter==FALSE)

covariates <- c("numberTexClone", "numberTregClone", "Texp.in.Tex.relevant", "Treg_CCR8", "PRR", "histology")
univ_formulas <- sapply(covariates,
                        function(x) as.formula(paste('Surv(RFS_months_new, RFS_status_new)~', x)))
                        
univ_models <- lapply( univ_formulas, function(x){coxph(x, data = fit.data)})
# Extract data 
univ_results <- lapply(univ_models,
                       function(x){ 
                          x <- summary(x)
                          p.value<-signif(x$wald["pvalue"], digits=2)
                          #wald.test<-signif(x$wald["test"], digits=2)
                          #beta<-signif(x$coef[1], digits=2);#coeficient beta
                          HR <-signif(x$coef[2], digits=2);#exp(beta)
                          HR.confint.lower <- signif(x$conf.int[,"lower .95"], 2)
                          HR.confint.upper <- signif(x$conf.int[,"upper .95"],2)
                          # HR <- paste0(HR, " (", 
                          #             HR.confint.lower, "-", HR.confint.upper, ")")
                          res<-c(HR, HR.confint.lower, HR.confint.upper, p.value)
                          names(res)<-c("HR", "HR.lower", "HR.upper", 
                                        "p.value")
                          return(res)
                          #return(exp(cbind(coef(x),confint(x))))
                         })
univ_results
result <- as.data.frame(univ_results)
result <- as.data.frame(t(result))
result #%>% filter(p.value <0.05)

tabletext1<-as.character(rownames(result))
tabletext2<-as.numeric(result[,"p.value"])
tabletext<-cbind(tabletext1,tabletext2)


forestplot(labeltext=tabletext, #文本信息  
           mean = result[,'HR'],##HR值
lower = result[,"HR.lower"],##95%置信区间
upper = result[,"HR.upper"],,#95%置信区间
           boxsize = 0.1,##大小
           graph.pos=3,#图在表中的列位置
           graphwidth = unit(0.4,"npc"),#图在表中的宽度比例
           #fn.ci_norm="fpDrawDiamondCI",#box类型选择钻石,可以更改fpDrawNormalCI；fpDrawCircleCI等
col=fpColors(box="steelblue", lines="black", zero = "black"),#颜色设置
           lwd.ci=2,ci.vertices.height = 0.1,ci.vertices=TRUE,#置信区间用线宽、高、型
           zero=1,#zero线横坐标
           lwd.zero=2,#zero线宽
           grid=T,
           lwd.xaxis=2,#X轴线宽
           title="Hazard Ratio",
           xlab="",#X轴标题
           clip=c(-Inf,4),#边界
           colgap = unit(0.5,"cm")   
)

fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$TCR.classification, data = fit.data)
summary(fit.cox)


```

```{r}
ggplot(survival.metadata.clean %>% filter(MPR=="MPR"), aes(x=Texp.in.Tex.relevant)) + geom_histogram()
quantile(survival.metadata.clean$Texp.in.Tex.relevant, na.rm = T)
```


```{r}
temp.data <- survival.metadata.clean %>% filter(MPR=="non-MPR")
fit.data <- survival.metadata.clean %>% mutate(Texp.in.Tex.relevant.bin= ifelse(MPR=="MPR", "MPR",
                                                                                ifelse(
  Texp.in.Tex.relevant < as.vector(quantile(temp.data$Texp.in.Tex.relevant,na.rm=T)[3]),
  "<top 50%", ">= top50%" # the quantile of survival analysis cohort and nmf cohort are almost the same
)))

fit.data <- fit.data
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ factor(fit.data$Texp.in.Tex.relevant.bin, levels=c("MPR", ">= top50%", "<top 50%")), data = fit.data)
summary(fit.cox)

fit <- survfit(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~ fit.data$Texp.in.Tex.relevant.bin, data = fit.data)
p <- ggsurvplot(fit,
          pval = TRUE, conf.int = FALSE,
          risk.table = TRUE, # Add risk table
          risk.table.col = "strata", # Change risk table color by groups
          linetype = "solid", # Change line type by groups
          #surv.median.line = "hv", # Specify median survival
          ggtheme = theme_classic(), # Change ggplot2 theme
          risk.table.pos = "in",
          xlab = "Months from surgery",
          title = "all.non-MPR.by.Texp",
          palette =  c("#C6595A", "#077E64","#D9BFAE")
)
p
ggsave("final_plots/all.non-MPR.by.Texp.pdf", width = 8, height = 6)


fit.data %>% group_by(Texp.in.Tex.relevant.bin) %>% count(PRR_group)
```


```{r}
plot.data <- fit.data %>% filter(Texp.in.Tex.relevant.bin %in% c("<top 50%", ">= top50%")) %>% mutate(value=1, PRR_group=factor(PRR_group, levels = c("pPR", "nPR")))
plot.data 
ggplot(plot.data, aes(fill=PRR_group, y=value, x=Texp.in.Tex.relevant.bin)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=c("#878586","#C6595A")) + theme_classic()

ggsave("final_plots/pPRnPR_Texp.pdf", width = 3, height = 4)


plot.data <- fit.data %>% filter(Texp.in.Tex.relevant.bin %in% c("<top 50%", ">= top50%")) %>% mutate(value=1, histology=factor(histology, levels = c("LUSC", "LUAD")))
plot.data 
ggplot(plot.data, aes(fill=histology, y=value, x=Texp.in.Tex.relevant.bin)) + 
    geom_bar(position="stack", stat="identity") + scale_fill_manual(values=c("#E97777","#88AB8E")) + theme_classic()

ggsave("final_plots/LUSCLUAD_Texp.pdf", width = 3, height = 4)
```


```{r}
pdf("final_plots/non-MPR.patients.ROC.pdf",         # File name
    width = 5, height = 5, # Width and height in inches
    bg = "white",    # Color model (cmyk is required for most publications)
    paper = "A4")  
fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant),MPR=="non-MPR")
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Texp.in.Tex.relevant, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf.texp <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months), method="Cox",col="#418849",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
#tROC.hf.texp$AUC


fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant),MPR=="non-MPR")
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$PRR, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf.prr <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months), method="Cox",col="blue",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
#tROC.hf.prr$AUC


lines(tROC.hf.texp$FP, tROC.hf.texp$TP, type="l",col="#418849",xlim=c(0,1), ylim=c(0,1))
lines(tROC.hf.prr$FP, tROC.hf.prr$TP, type="l",col="blue",xlim=c(0,1), ylim=c(0,1))
legend("bottomright",c(paste("AUC of texp: ",round(tROC.hf.texp$AUC,3)), paste("AUC of PRR : ",round(tROC.hf.prr$AUC,3))),col=c("#418849","blue"),lty=1,lwd=2,bty = "n") 
dev.off()
```


```{r}
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Surgery_N, data = fit.data)
summary(fit.cox)

fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Surgery_N + fit.data$Texp.in.Tex.relevant, data = fit.data)
summary(fit.cox)

fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$PRR + fit.data$Texp.in.Tex.relevant, data = fit.data)
summary(fit.cox)


fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant))
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Texp.in.Tex.relevant, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months_new), method="Cox",col="green",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
tROC.hf$AUC


fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant))
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$PRR, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months_new), method="Cox",col="green",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
tROC.hf$AUC

fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant))
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Texp.in.Tex.relevant + fit.data$Surgery_N, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months_new), method="Cox",col="green",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
tROC.hf$AUC

fit.data <- fit.data %>% filter(!is.na(Texp.in.Tex.relevant))
fit.cox <- coxph(Surv(fit.data$RFS_months_new, fit.data$RFS_status_new) ~  fit.data$Surgery_N, data = fit.data)
PI<-fit.cox$linear.predictor
tROC.hf <-risksetROC(Stime=fit.data$RFS_months_new,status=fit.data$RFS_status_new,marker=PI, predict.time = median(fit.data$RFS_months_new), method="Cox",col="green",lty=1,lwd=1, xlab="FP:1-Specificity",ylab="TP:sensitivity",main="Time Dependent ROC")
tROC.hf$AUC
```









